config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :llinks do
    member do
      put "like", to: "llinks#upvote"
      put "dislike", to: "llinks#downvote"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root('llinks#index')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/llink.rb
class Llink < ApplicationRecord
  belongs_to :user
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :llinks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/llinks_controller.rb
class LlinksController < ApplicationController
  before_action :set_llink, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /llinks
  # GET /llinks.json
  def index
    @llinks = Llink.all
  end

  # GET /llinks/1
  # GET /llinks/1.json
  def show
  end

  # GET /llinks/new
  def new
    @llink = current_user.llinks.build
  end

  # GET /llinks/1/edit
  def edit
  end

  # POST /llinks
  # POST /llinks.json
  def create
    @llink = current_user.llinks.build(llink_params)

    respond_to do |format|
      if @llink.save
        format.html { redirect_to @llink, notice: 'Llink was successfully created.' }
        format.json { render :show, status: :created, location: @llink }
      else
        format.html { render :new }
        format.json { render json: @llink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /llinks/1
  # PATCH/PUT /llinks/1.json
  def update
    respond_to do |format|
      if @llink.update(llink_params)
        format.html { redirect_to @llink, notice: 'Llink was successfully updated.' }
        format.json { render :show, status: :ok, location: @llink }
      else
        format.html { render :edit }
        format.json { render json: @llink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /llinks/1
  # DELETE /llinks/1.json
  def destroy
    @llink.destroy
    respond_to do |format|
      format.html { redirect_to llinks_url, notice: 'Llink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @llink = Llink.find(params[:id])
    @llink.upvote_by current_user
    redirect_back fallback_location: root_path
  end

  def downvote
    @llink = Llink.find(params[:id])
    @llink.downvote_by current_user
    redirect_back fallback_location: root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_llink
      @llink = Llink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def llink_params
      params.require(:llink).permit(:title, :url)
    end

   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/llinks_helper.rb
module LlinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "Raddit", root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
          <% if user_signed_in? -%>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Submit link', new_llink_path %></li>
              <li><%= link_to 'Account', edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            </ul>
          <% else -%>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            </ul>
          <% end -%>
        </nav>
      </div>
    </div>
  </header>
<div id="main_content" class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
<div id="content" class="col-md-9 center-block">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/llinks/_form.html.erb
<%= form_with(model: llink, local: true) do |form| %>
  <% if llink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(llink.errors.count, "error") %> prohibited this link from being saved:</h2>
<ul>
      <% llink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
<div class="form-group">
    <%= form.label :url %><br>
    <%= form.text_field :url, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-kg btn-primary" %>
  </div>
<% end %>

app/views/llinks/edit.html.erb
<h1>Editing Llink</h1>

<%= render 'form', llink: @llink %>

<%= link_to 'Show', @llink %> |
<%= link_to 'Back', llinks_path %>

app/views/llinks/index.html.erb
<% @llinks.each do |llink| %>
  <div class="link row clearfix">
    <h2>
        <%= link_to llink.title, llink %><br>
        <small class="author">Submitted <%= time_ago_in_words(llink.created_at) %> by <%= llink.user.email %></small>
    </h2>
<div class="btn-group">
      <a class="btn btn-default btn-sm" href="<%= llink.url %>">Visit Link</a>
      <%= link_to like_llink_path(llink), method: :put, class: "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-chevron-up"></span>
      Upvote
      <%= llink.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_llink_path(llink), method: :put, class: "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-chevron-down"></span>
      Downvote
      <%= llink.get_downvotes.size %>
       <% end %>
    </div>
   </div>
  <% end %>

app/views/llinks/new.html.erb
<h1>New Llink</h1>

<%= render 'form', llink: @llink %>

<%= link_to 'Back', llinks_path %>

app/views/llinks/show.html.erb
<div class="page-header">
 <h1><a href="<%= @llink.url %>"><%= @llink.title %></a><br> <small>Submitted by <%= @llink.user.email %></small></h1>
</div>
<div class="btn-group">
 <%= link_to 'Visit URL', @llink.url, class: "btn btn-primary" %>
</div>
<% if @llink.user == current_user %>
 <div class="btn-group">
  <%= link_to 'Edit', edit_llink_path(@llink), class: "btn btn-default" %>
  <%= link_to 'Destroy', @llink, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
 </div>
<% end %>
<div class="btn-group pull-right">
 <%= link_to like_llink_path(@llink), method: :put, class: "btn btn-default btn-sm" do %>
  <span class="glyphicon glyphicon-chevron-up"></span>
  Upvote
  <%= @llink.get_upvotes.size %>
 <% end %>
 <%= link_to dislike_llink_path(@llink), method: :put, class: "btn btn-default btn-sm" do %>
  <span class="glyphicon glyphicon-chevron-down"></span>
  Downvote
  <%= @llink.get_downvotes.size %>
 <% end %>
</div>